/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Principales;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;

/**
 *
 * @author Angel
 */
public class Diseño extends javax.swing.JFrame {

    /**
     * Creates new form Diseño
     */
    public Diseño() {
        initComponents();
        //GraphicsDevice dev = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        //dev.setFullScreenWindow(this);
        grupo.add(radio_Draw);
        grupo.add(radio_fill);
        radio_Draw.setSelected(true);
        grupo_relleno.add(radio_color);
        grupo_relleno.add(radio_gradient);
        radio_color.setSelected(true);
    }
    
    private DefaultComboBoxModel getModel(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("simple");
        model.addElement("medio");
        model.addElement("completo");
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        grupo = new javax.swing.ButtonGroup();
        grupo_relleno = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        panel_Herramientas = new javax.swing.JPanel();
        slide_transparencia = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        radio_Draw = new javax.swing.JRadioButton();
        radio_fill = new javax.swing.JRadioButton();
        comboBox_Stroke = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelColor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_Gradiel1 = new javax.swing.JPanel();
        panelGradiel2 = new javax.swing.JPanel();
        radio_color = new javax.swing.JRadioButton();
        radio_gradient = new javax.swing.JRadioButton();
        panel_Figuras = new javax.swing.JPanel();
        boton_Arco = new javax.swing.JButton();
        boton_Elipse = new javax.swing.JButton();
        boton_linea = new javax.swing.JButton();
        boton_QuaCurv = new javax.swing.JButton();
        botton_roundRectangle = new javax.swing.JButton();
        botton_square = new javax.swing.JButton();
        botton_triangle = new javax.swing.JButton();
        panel_Movimientos = new javax.swing.JPanel();
        boton_up = new javax.swing.JButton();
        boton_Derecha = new javax.swing.JButton();
        boton_Izquierda = new javax.swing.JButton();
        boton_abajo = new javax.swing.JButton();
        boton_escalarIncrement = new javax.swing.JButton();
        boton_Decremento = new javax.swing.JButton();
        botonRotarDerecha = new javax.swing.JButton();
        botonRotarIzquierda = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        canvas = new Principales.CustomCanvas();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panel_Herramientas.setBackground(new java.awt.Color(204, 204, 204));
        panel_Herramientas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        slide_transparencia.setValue(100);
        slide_transparencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slide_transparenciaStateChanged(evt);
            }
        });

        jLabel1.setText("Transparencia");

        radio_Draw.setText("Draw");
        radio_Draw.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_DrawItemStateChanged(evt);
            }
        });
        radio_Draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_DrawActionPerformed(evt);
            }
        });

        radio_fill.setText("Fill");
        radio_fill.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_fillItemStateChanged(evt);
            }
        });

        comboBox_Stroke.setModel(this.getModel());
        comboBox_Stroke.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBox_StrokeItemStateChanged(evt);
            }
        });

        jLabel2.setText("Stroke");

        jLabel3.setText("Color");

        panelColor.setBackground(new java.awt.Color(0, 0, 0));
        panelColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jLabel4.setText("Gradient");

        panel_Gradiel1.setBackground(new java.awt.Color(0, 51, 255));
        panel_Gradiel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_Gradiel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_Gradiel1Layout = new javax.swing.GroupLayout(panel_Gradiel1);
        panel_Gradiel1.setLayout(panel_Gradiel1Layout);
        panel_Gradiel1Layout.setHorizontalGroup(
            panel_Gradiel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        panel_Gradiel1Layout.setVerticalGroup(
            panel_Gradiel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelGradiel2.setBackground(new java.awt.Color(0, 153, 0));
        panelGradiel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGradiel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelGradiel2Layout = new javax.swing.GroupLayout(panelGradiel2);
        panelGradiel2.setLayout(panelGradiel2Layout);
        panelGradiel2Layout.setHorizontalGroup(
            panelGradiel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        panelGradiel2Layout.setVerticalGroup(
            panelGradiel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        radio_color.setText("Color");
        radio_color.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_colorItemStateChanged(evt);
            }
        });

        radio_gradient.setText("Gradient");
        radio_gradient.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_gradientItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel_HerramientasLayout = new javax.swing.GroupLayout(panel_Herramientas);
        panel_Herramientas.setLayout(panel_HerramientasLayout);
        panel_HerramientasLayout.setHorizontalGroup(
            panel_HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_HerramientasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comboBox_Stroke, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_Draw, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radio_fill, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_gradient)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Gradiel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGradiel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slide_transparencia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_HerramientasLayout.setVerticalGroup(
            panel_HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_HerramientasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Gradiel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio_fill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio_Draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(comboBox_Stroke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio_color)
                        .addComponent(radio_gradient))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_HerramientasLayout.createSequentialGroup()
                        .addGroup(panel_HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slide_transparencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelGradiel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_Figuras.setBackground(new java.awt.Color(204, 204, 204));
        panel_Figuras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        boton_Arco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/arco4.png"))); // NOI18N
        boton_Arco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ArcoActionPerformed(evt);
            }
        });

        boton_Elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elipce2.png"))); // NOI18N
        boton_Elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ElipseActionPerformed(evt);
            }
        });

        boton_linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        boton_linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_lineaActionPerformed(evt);
            }
        });

        boton_QuaCurv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/quacurve.png"))); // NOI18N
        boton_QuaCurv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_QuaCurvActionPerformed(evt);
            }
        });

        botton_roundRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/roudrec.png"))); // NOI18N
        botton_roundRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_roundRectangleActionPerformed(evt);
            }
        });

        botton_square.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cuadro.png"))); // NOI18N
        botton_square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_squareActionPerformed(evt);
            }
        });

        botton_triangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/triangulo.png"))); // NOI18N
        botton_triangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_triangleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_FigurasLayout = new javax.swing.GroupLayout(panel_Figuras);
        panel_Figuras.setLayout(panel_FigurasLayout);
        panel_FigurasLayout.setHorizontalGroup(
            panel_FigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FigurasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_FigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botton_triangle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_FigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_FigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boton_linea, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_Elipse, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_Arco, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_QuaCurv, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botton_roundRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_FigurasLayout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(botton_square, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panel_FigurasLayout.setVerticalGroup(
            panel_FigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FigurasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton_Arco)
                .addGap(18, 18, 18)
                .addComponent(boton_Elipse, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_linea, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_QuaCurv, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botton_roundRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botton_square, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botton_triangle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_Movimientos.setBackground(new java.awt.Color(204, 204, 204));
        panel_Movimientos.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        boton_up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/flechaAR.png"))); // NOI18N
        boton_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_upActionPerformed(evt);
            }
        });

        boton_Derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/flechaDe.png"))); // NOI18N
        boton_Derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_DerechaActionPerformed(evt);
            }
        });

        boton_Izquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/flechaIz.png"))); // NOI18N
        boton_Izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_IzquierdaActionPerformed(evt);
            }
        });

        boton_abajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/flechaAB.png"))); // NOI18N
        boton_abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_abajoActionPerformed(evt);
            }
        });

        boton_escalarIncrement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupaMAs.png"))); // NOI18N
        boton_escalarIncrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_escalarIncrementActionPerformed(evt);
            }
        });

        boton_Decremento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupame.png"))); // NOI18N
        boton_Decremento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_DecrementoActionPerformed(evt);
            }
        });

        botonRotarDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/flechaRT.png"))); // NOI18N
        botonRotarDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRotarDerechaActionPerformed(evt);
            }
        });

        botonRotarIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/flechaTIZ.png"))); // NOI18N
        botonRotarIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRotarIzquierdaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ultimo12.png"))); // NOI18N

        javax.swing.GroupLayout panel_MovimientosLayout = new javax.swing.GroupLayout(panel_Movimientos);
        panel_Movimientos.setLayout(panel_MovimientosLayout);
        panel_MovimientosLayout.setHorizontalGroup(
            panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MovimientosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MovimientosLayout.createSequentialGroup()
                        .addComponent(boton_up, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MovimientosLayout.createSequentialGroup()
                        .addComponent(boton_abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MovimientosLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(boton_Izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(boton_Derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_MovimientosLayout.createSequentialGroup()
                .addGroup(panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_MovimientosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_escalarIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRotarIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_Decremento, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRotarDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_MovimientosLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_MovimientosLayout.setVerticalGroup(
            panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MovimientosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(boton_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_Derecha)
                    .addComponent(boton_Izquierda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_escalarIncrement)
                    .addComponent(boton_Decremento))
                .addGap(32, 32, 32)
                .addGroup(panel_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRotarIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRotarDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Herramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Figuras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Figuras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Movimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_DrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_DrawActionPerformed
        canvas.setDraw(radio_Draw.isSelected());
    }//GEN-LAST:event_radio_DrawActionPerformed

    private void botton_squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_squareActionPerformed
        canvas.setPolygonPaint(4);
    }//GEN-LAST:event_botton_squareActionPerformed

    private void botonRotarDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRotarDerechaActionPerformed
        canvas.rotationRight();
    }//GEN-LAST:event_botonRotarDerechaActionPerformed

    private void boton_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_upActionPerformed
        canvas.moveUp();
    }//GEN-LAST:event_boton_upActionPerformed

    private void boton_ArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ArcoActionPerformed
        canvas.setPolygonPaint(6);
    }//GEN-LAST:event_boton_ArcoActionPerformed

    private void boton_ElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ElipseActionPerformed
       canvas.setPolygonPaint(5);
    }//GEN-LAST:event_boton_ElipseActionPerformed

    private void boton_lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_lineaActionPerformed
        canvas.setPolygonPaint(0);
    }//GEN-LAST:event_boton_lineaActionPerformed

    private void boton_QuaCurvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_QuaCurvActionPerformed
        canvas.setPolygonPaint(1);
    }//GEN-LAST:event_boton_QuaCurvActionPerformed

    private void botton_roundRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_roundRectangleActionPerformed
        canvas.setPolygonPaint(3);
    }//GEN-LAST:event_botton_roundRectangleActionPerformed

    private void botton_triangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_triangleActionPerformed
        canvas.setPolygonPaint(2);
    }//GEN-LAST:event_botton_triangleActionPerformed

    private void boton_abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_abajoActionPerformed
        canvas.moveDown();
    }//GEN-LAST:event_boton_abajoActionPerformed

    private void boton_IzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_IzquierdaActionPerformed
        canvas.moveleft();
    }//GEN-LAST:event_boton_IzquierdaActionPerformed

    private void boton_DerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_DerechaActionPerformed
        canvas.moveRight();
    }//GEN-LAST:event_boton_DerechaActionPerformed

    private void boton_escalarIncrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_escalarIncrementActionPerformed
        canvas.scaleUp();
    }//GEN-LAST:event_boton_escalarIncrementActionPerformed

    private void boton_DecrementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_DecrementoActionPerformed
        canvas.scaleDown();
    }//GEN-LAST:event_boton_DecrementoActionPerformed

    private void botonRotarIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRotarIzquierdaActionPerformed
        canvas.rotationLeft();
    }//GEN-LAST:event_botonRotarIzquierdaActionPerformed

    private void comboBox_StrokeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBox_StrokeItemStateChanged
        canvas.setStroke(comboBox_Stroke.getSelectedIndex());
    }//GEN-LAST:event_comboBox_StrokeItemStateChanged

    private void radio_DrawItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_DrawItemStateChanged
          
    }//GEN-LAST:event_radio_DrawItemStateChanged

    private void radio_fillItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_fillItemStateChanged
       canvas.setFill(radio_fill.isSelected());
    }//GEN-LAST:event_radio_fillItemStateChanged

    private void panelColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelColorMouseClicked
        Color aux = JColorChooser.showDialog(boton_up, "selecciona tu color", Color.black);
        canvas.setC(aux);
        panelColor.setBackground(aux);
    }//GEN-LAST:event_panelColorMouseClicked

    private void radio_colorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_colorItemStateChanged
        canvas.setIsColor(radio_color.isSelected());
    }//GEN-LAST:event_radio_colorItemStateChanged

    private void radio_gradientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_gradientItemStateChanged
       canvas.setIsGradient(radio_gradient.isSelected());
    }//GEN-LAST:event_radio_gradientItemStateChanged

    private void panel_Gradiel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_Gradiel1MouseClicked
        Color aux = JColorChooser.showDialog(boton_up, "selecciona el primer color del gradient", Color.blue);
        canvas.setOne(aux);
        panel_Gradiel1.setBackground(aux);
    }//GEN-LAST:event_panel_Gradiel1MouseClicked

    private void panelGradiel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradiel2MouseClicked
        Color aux = JColorChooser.showDialog(boton_up, "selecciona el segundo color del gradient", Color.green);
        canvas.setTwo(aux);
        panelGradiel2.setBackground(aux);
    }//GEN-LAST:event_panelGradiel2MouseClicked

    private void slide_transparenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slide_transparenciaStateChanged
        float x = slide_transparencia.getValue();
        x = x/100;
        canvas.setComposite(x);
    }//GEN-LAST:event_slide_transparenciaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diseño().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRotarDerecha;
    private javax.swing.JButton botonRotarIzquierda;
    private javax.swing.JButton boton_Arco;
    private javax.swing.JButton boton_Decremento;
    private javax.swing.JButton boton_Derecha;
    private javax.swing.JButton boton_Elipse;
    private javax.swing.JButton boton_Izquierda;
    private javax.swing.JButton boton_QuaCurv;
    private javax.swing.JButton boton_abajo;
    private javax.swing.JButton boton_escalarIncrement;
    private javax.swing.JButton boton_linea;
    private javax.swing.JButton boton_up;
    private javax.swing.JButton botton_roundRectangle;
    private javax.swing.JButton botton_square;
    private javax.swing.JButton botton_triangle;
    private Principales.CustomCanvas canvas;
    private javax.swing.JComboBox comboBox_Stroke;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.ButtonGroup grupo_relleno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelGradiel2;
    private javax.swing.JPanel panel_Figuras;
    private javax.swing.JPanel panel_Gradiel1;
    private javax.swing.JPanel panel_Herramientas;
    private javax.swing.JPanel panel_Movimientos;
    private javax.swing.JRadioButton radio_Draw;
    private javax.swing.JRadioButton radio_color;
    private javax.swing.JRadioButton radio_fill;
    private javax.swing.JRadioButton radio_gradient;
    private javax.swing.JSlider slide_transparencia;
    // End of variables declaration//GEN-END:variables
}
